[package]
name = "dlhook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goblin = "0.6.0"
once_cell = "1.15.0"
procfs = "0.14.1"
